M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu20.04.1} date Mon 05 Dec 2022 10:15:58 PM GMT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-05T22:15:58+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.9118Y-4.6862
X4.1394Y-4.6862
T0
M30
